### ISSUE TITLE
Provide access

### ISSUE THREAD

**Issue by renanmav** [fabriziobertoglio1987/hackathon-team#15]
Hi @fabriziobertoglio1987 and @ProBeta1,

Currently, we have a problem regarding access control. Can we create a GitHub org to leverage GitHub teams?

I can’t access your private repo and kanban @fabriziobertoglio1987, neither your tech specs @ProBeta1.

**Comment by ProBeta1** [comment]
You have access for the docs now , regarding the repo , check [this] .(https://github.com/fabriziobertoglio1987/hackathon-team/issues/11#issuecomment-640225328)

**Comment by fabriziobertoglio1987** [comment]
start working on one of the issues from the [kanban](https://github.com/fabriziobertoglio1987/hackathon-team/projects/2) board otherwise build y own repo, create a separate kanban board in this [repo](https://github.com/fabriziobertoglio1987/hackathon-team/projects) for your new project and create a list of clear feature requests so that we can collaborate with you.

Repo is private and only collaborators will have access until we registered the team that will present

You need to merge at least 1-2 pull requests to be in my team, otherwise I'll present alone

But I'm happy to just merge 1-2 pull request in your repo and presents 2 products for this hackathon :smile:  

I'm busy now, no need for an organization, we have 4 stars.. Just pick a task that you want to do to the kanban board, give me deadline and tell me how you would implement it in 3 lines and i'll give you access 

[kanban board](https://github.com/fabriziobertoglio1987/hackathon-team/projects/2)

Please don't reply to this message here, just pick an issue

thanks

**Comment by fabriziobertoglio1987** [comment]
I updated readme and added a [project section](https://github.com/fabriziobertoglio1987/hackathon-team#projects---1-week-left-to-registration). 

I will register a team in 1 week and I have already a product built. Please review the [guides here to be part of my team](https://github.com/fabriziobertoglio1987/hackathon-team/blob/master/projects/virtual-assistant.markdown) 

DEADLINE is 24 June so we need to register in 1 week. 

If you want to built a different project, you can add it to the readme in the [project section](https://github.com/fabriziobertoglio1987/hackathon-team#projects---1-week-left-to-registration). 

Thanks. Have a good week. Fabrizio
