### ISSUE TITLE
Facebook Developers Review Process

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [fabriziobertoglio1987/hackathon-team#28]
I would like to assign this task to @gittycoder01 

This is a NON CODING TASK. You don't need to code or undestand any technical aspects of the app. You only need to estimate for us and organize the process of App Review with Facebook.

as discussed in https://github.com/fabriziobertoglio1987/hackathon-team/issues/20#issuecomment-642802216 every time we get some information on Facebook Users we need to get the authorization from the User and from Facebook.

Facebook has a review process, which takes on average 5-6 days.

They will check that the Apps has Privacy Policy and they will check other things...

Please read about this and prepare a list of TODOs that we need to add to our [KanBan Board](https://github.com/fabriziobertoglio1987/hackathon-team/projects/2) and please tell us how much will the review process take so we can organize it. The due date for our app is 24th of June.

The review process. **IMPORTANT**
https://developers.facebook.com/docs/facebook-login/permissions/review

We will probably do the Private Policy with the below site (if it is necessary)..but I never used it
https://www.iubenda.com/en/

To see a list of the different type of permissions. Every time you get some information from the user, you will ask him before hand to grant you access to those informations

For example, I want to get the list of your friends, I need to get user_friends permission
https://developers.facebook.com/docs/facebook-login/permissions/ 

Please contact me and @zejiran for help and clarifications.
Thanks a lot
Fabrizio

**Comment by gittycoder01** [comment]
Good Day fabriziobertoglio1987 !

ToDo: 
1. We need to consolidate all the facebook permissions we need in our app since each 
permission has its own set of requirements and usage that are subject to Facebook Platform Policies 

2. We implement each Facebook Platform Policies for each permissions

For example for issue #20
we need permisssion: user_location			
The user_location permission allows your app to read the city name as listed in the location field of a person's Facebook profile.

Allowed Usage
Provide a personalized experience based on the city name as listed in the location field of a person's Facebook profile.
											  
3. According to FB, review process requires 3 days, 7 days for some permission.
I searched to quora, stack overflow etc. Some answers it took only 2 hrs (that app has 40k users, and has reviewed before.. resubmitted) but many was saying they have passed the review process for 1 week.

With that I think the best thing to do is to fulfill all Facebook Platform Policies within June 16- 17 or earlier

4. We can now submit our app for review 
https://developers.facebook.com/docs/facebook-login/review/how-to-submit/
To make submission process as easy as possible we might as well follow these guidelines:
https://developers.facebook.com/docs/apps/review/submission-guidelines


USER PERMISSIONS AND ALLOWED USAGE:

Retrieve Facebook Friends #18 
-> user_friends
	Allowed Usage:
		1. Providing Facebook-related content to personalize a person's experience.

Facebook Send Message #27 
-> pages_messaging
	Allowed Usage:
		1. Create interactive experiences initiated by a User.
		2. Confirm customer interactions such as purchases, orders, and bookings.
		3. Send customer support messages.

Facebook Graph API (events, calendar..) #13 
-> publish_to_groups
		1. Allow people to publish content from your app to their Facebook group.
		2. Help people manage the content published to their group.
-> groups_access_member_info
		1. Allow apps to get content posted in their group with user details.
		2. Help admins get aggregated insights about activity happening in their group.


Details
Before you can submit for approval, you will be asked to describe how you will use the data provided by each permission or feature. 
If you set up Test Users to test these permissions or features, it's a good idea to include their login credentials with your submission.
Give a thorough explanation of how your app uses each permission. Try using these questions as a starting point:

How will granting this permission help the people using your app?
Why do you need this permission?
How will your app use the data it receives from Facebook?
How does your app use the permission?
Why would your app be less useful if it did not have this permission?
Be very specific.

Screencast
Some permissions and features require a screencast that demonstrates how your app will use the data (or for apps that have no UI, how the data will ultimately be used). 
We recommend that you use dedicated screencast software in order to capture your screencast.
Avoid using a mobile device's camera to record the screen of another device that shows your app flow. The easiest way to show data usage is to set your app to development mode and pull data from your own User account, or from any Users who have an Admin or Developer role on your app.
If your app has no user interface and interacts directly with our APIs, refer to our Server-to-Server Apps document for guidelines when providing details.

**Comment by fabriziobertoglio1987** [comment]
Thanks a lot @gittycoder01 I am really thankful as all this facebook permissions and app reviews has allways been my biggest headache 

This is a really good analysis. 

My questions are:

1) Can we submit a mobile app that is not 100% finished by the 17th of June?
2) Can we submit a mobile app that is still not approved/released/published from Google Play and Apple Store? 

Giving a screencast or providing a test user is not an issue, as all those tasks are required by the google play/apple store for publishing.

**There are a couple of things I don't find in your analysis**:

1) Privacy Policy which includes explanation on how we treat the information received from facebook
2) [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) also needs to explain how we treat the user information in our database (including those obtained from Facebook)

https://stackoverflow.com/questions/44764212/how-should-i-deal-with-the-facebook-app-privacy-policy-url-in-developers-page
https://www.iubenda.com/en/help/13561-privacy-policy-for-facebook-apps

https://www.termsfeed.com/blog/privacy-policy-url-facebook-app/
https://www.freeprivacypolicy.com/blog/facebook-app-privacy-policy/

**Comment by fabriziobertoglio1987** [comment]
as explained in https://github.com/fabriziobertoglio1987/hackathon-team/issues/29#issue-637534393 it should be no problem generating privacy policy with iubenda 

so I would close this issue and I will do https://github.com/fabriziobertoglio1987/hackathon-team/issues/29 with @gittycoder01 on [iubenda](https://www.iubenda.com/en/help/13561-privacy-policy-for-facebook-apps) around the 26th of June

Thanks a lot for the great work
